/* Live data and actions for the management workspace. */
(() => {
  const page = window.location.pathname.split('/').pop() || '';
  const managed = new Set(['absensi.html', 'santri.html', 'materi.html', 'kepegawaian.html', 'tahfidz.html', 'nilai.html', 'keuangan.html', 'cms.html', 'analitik.html', 'notifikasi.html', 'pengaturan.html']);
  if (!managed.has(page)) return;
  const state = { students: [], classes: [], staff: [], records: {}, content: [], attendance: null, summary: null, editingContent: null };
  let installPrompt = null;
  window.addEventListener('beforeinstallprompt', event => { event.preventDefault(); installPrompt = event; });
  const portal = () => window.DarussolahPortal;
  const safe = value => String(value ?? '').replace(/[&<>"']/g, character => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[character]));
  const initials = value => String(value || 'SN').trim().split(/\s+/).map(part => part[0]).join('').slice(0, 2).toUpperCase();
  const toast = (title, detail) => {
    const node = document.getElementById('toast');
    if (!node) return;
    const titleNode = node.querySelector('#toastTitle, #toast-title');
    const detailNode = node.querySelector('#toastText, #toast-detail');
    if (titleNode) titleNode.textContent = title;
    if (detailNode) detailNode.textContent = detail;
    node.classList.add('show');
    window.clearTimeout(node._timer);
    node._timer = window.setTimeout(() => node.classList.remove('show'), 3600);
  };
  const api = (suffix, options = {}) => {
    const p = portal();
    if (!p?.requestPrivate) return Promise.reject(new Error('sesi portal belum siap'));
    return p.requestPrivate(p.client, suffix, p.session, options);
  };
  const json = (method, body) => ({ method, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) });
  const closeModal = id => { const modal = document.getElementById(id); if (modal) { modal.hidden = true; modal.setAttribute('aria-hidden', 'true'); } };
  const openModal = id => { const modal = document.getElementById(id); if (modal) { modal.hidden = false; modal.setAttribute('aria-hidden', 'false'); modal.querySelector('input,textarea')?.focus(); } };
  const download = (name, text, type = 'text/csv;charset=utf-8') => {
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([text], { type }));
    link.download = name; link.click(); URL.revokeObjectURL(link.href);
  };
  const csv = rows => rows.map(row => row.map(value => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
  const fmtMoney = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(Number(value) || 0);
  const fmtDate = value => value ? new Intl.DateTimeFormat('id-ID', { day: '2-digit', month: 'short', year: 'numeric' }).format(new Date(value)) : '—';
  const setText = (id, value) => { const node = document.getElementById(id); if (node) node.textContent = String(value ?? ''); };
  const markLive = selector => document.querySelectorAll(selector).forEach(node => { if (/data contoh/i.test(node.textContent)) node.textContent = 'DATA LIVE'; node.dataset.portalLive = 'true'; });
  const markLiveNode = node => { if (node) { if (/data contoh/i.test(node.textContent)) node.textContent = 'DATA LIVE'; node.dataset.portalLive = 'true'; } };
  const records = async module => {
    const response = await api(`admin/records?module=${encodeURIComponent(module)}`);
    state.records[module] = response.items || [];
    return state.records[module];
  };
  const saveRecord = (module, recordKey, payload, entityId = null) => api('admin/records', json('POST', { module, record_key: recordKey, entity_id: entityId, payload }));
  const institutions = () => {
    const list = [];
    state.classes.forEach(item => { if (item.institution_id && !list.some(existing => existing.id === item.institution_id)) list.push({ id: item.institution_id, name: item.institution_name || item.institution_code }); });
    (portal()?.context?.memberships || []).forEach(item => { if (item.institution_id && !list.some(existing => existing.id === item.institution_id)) list.push({ id: item.institution_id, name: item.name || item.code }); });
    return list;
  };
  const primaryInstitutionId = () => portal()?.primaryClass?.institution_id || institutions()[0]?.id || '';

  const attendanceUi = { pending: 'belum', present: 'hadir', excused: 'izin', sick: 'sakit', absent: 'alpa', late: 'terlambat' };
  const attendanceApi = { belum: 'pending', hadir: 'present', izin: 'excused', sakit: 'sick', alpa: 'absent', terlambat: 'late' };
  const attendanceOptions = status => ['belum', 'hadir', 'izin', 'sakit', 'alpa', 'terlambat'].map(value => `<option value="${value}"${value === status ? ' selected' : ''}>${value === 'belum' ? 'Belum diisi' : value === 'hadir' ? 'Hadir' : value === 'izin' ? 'Izin' : value === 'sakit' ? 'Sakit' : value === 'alpa' ? 'Alpa' : 'Terlambat'}</option>`).join('');
  const timeLabel = value => value ? `${new Intl.DateTimeFormat('id-ID', { hour: '2-digit', minute: '2-digit', timeZone: 'Asia/Jakarta' }).format(new Date(value))} WIB` : '-';
  function updateAttendanceStats(rows) {
    const statuses = rows.map(row => row.dataset.status);
    const total = statuses.length;
    const attended = statuses.filter(status => ['hadir', 'terlambat'].includes(status)).length;
    const excused = statuses.filter(status => ['izin', 'sakit'].includes(status)).length;
    const pending = statuses.filter(status => status === 'belum').length;
    const percent = total ? Math.round((attended / total) * 100) : 0;
    setText('metric-total', String(total).padStart(2, '0')); setText('metric-present', String(attended).padStart(2, '0')); setText('metric-excused', String(excused).padStart(2, '0')); setText('metric-pending', String(pending).padStart(2, '0')); setText('metric-present-foot', `${percent}% dari kelas`);
    setText('legend-present', attended); setText('legend-excused', excused); setText('legend-pending', pending); setText('donut-value', `${percent}%`);
    const donut = document.querySelector('#donut-value')?.closest('.donut'); if (donut) donut.style.background = `conic-gradient(var(--green) 0 ${percent}%, #e8ece5 ${percent}% 100%)`;
  }
  function renderAttendance(response) {
    const rows = document.getElementById('student-rows'); if (!rows) return;
    const recordsByStudent = new Map((response?.records || []).map(item => [item.student_id, item]));
    const students = response?.students?.length ? response.students : state.students.filter(student => !response?.class?.id || student.class_id === response.class.id);
    rows.innerHTML = students.map(student => {
      const record = recordsByStudent.get(student.id) || {};
      const status = attendanceUi[record.status] || 'belum';
      return `<tr data-name="${safe(String(student.full_name || '').toLowerCase())}" data-status="${status}" data-attendance-student="${safe(student.id)}"><td><div class="student-cell"><span class="student-avatar">${safe(initials(student.full_name))}</span><span class="student-detail">${safe(student.full_name)}<small>${safe(response?.class?.name || student.nis || '')}</small></span></div></td><td><select class="status-select" data-status="${status}" aria-label="Status kehadiran ${safe(student.full_name)}">${attendanceOptions(status)}</select></td><td class="time-cell">${safe(timeLabel(record.recorded_at))}</td><td><button class="row-action" type="button" data-live-attendance="${safe(student.id)}" aria-label="Detail ${safe(student.full_name)}">…</button></td></tr>`;
    }).join('') || '<tr><td colspan="4">Belum ada santri di kelas ini.</td></tr>';
    state.attendance = response || null;
    const closed = response?.session?.status === 'closed'; rows.querySelectorAll('.status-select').forEach(select => { select.disabled = closed; }); const saveButton = document.getElementById('save-attendance'); if (saveButton) saveButton.disabled = closed; const closeButton = document.getElementById('close-session'); if (closeButton) { closeButton.disabled = closed; if (closed) closeButton.textContent = 'Sesi ditutup'; }
    updateAttendanceStats([...rows.querySelectorAll('tr[data-attendance-student]')]);
    markLive('.session-tag');
  }
  async function loadAttendance(response = portal()?.attendance) {
    const primaryClass = portal()?.primaryClass;
    if (!primaryClass) return;
    const data = response || await api(`attendance?class_id=${encodeURIComponent(primaryClass.id)}&attendance_date=${new Date().toISOString().slice(0, 10)}`);
    renderAttendance(data);
    const label = document.getElementById('today-label'); if (label) label.textContent = `${new Intl.DateTimeFormat('id-ID', { weekday: 'long', day: 'numeric', month: 'long', year: 'numeric' }).format(new Date())} · ${data.class?.name || primaryClass.name || 'Kelas aktif'}`;
  }
  async function persistAttendance(closeSession = false) {
    const primaryClass = portal()?.primaryClass;
    const rows = [...document.querySelectorAll('#student-rows tr[data-attendance-student]')];
    if (!primaryClass || !rows.length) return toast('Absensi belum siap', 'Data kelas atau santri belum termuat.');
    try {
      const response = await api('attendance', json('PUT', { class_id: primaryClass.id, attendance_date: new Date().toISOString().slice(0, 10), close_session: closeSession, records: rows.map(row => ({ student_id: row.dataset.attendanceStudent, status: attendanceApi[row.dataset.status] || 'pending' })) }));
      renderAttendance(response); const button = document.getElementById('close-session'); if (closeSession && button) button.textContent = 'Sesi ditutup';
      toast(closeSession ? 'Sesi absensi ditutup' : 'Absensi tersimpan', 'Status kehadiran sudah tersimpan di server.');
    } catch (error) { toast(closeSession ? 'Sesi belum ditutup' : 'Absensi belum tersimpan', error.message); }
  }

  async function loadStudents() {
    const response = await api('admin/students');
    state.students = response.items || [];
    const classSelect = document.getElementById('studentClass');
    if (classSelect && state.classes.length) classSelect.innerHTML = state.classes.map(item => `<option value="${safe(item.id)}">${safe(item.name || item.code)}</option>`).join('');
    renderStudents();
  }
  function renderStudents() {
    const rows = document.getElementById('studentRows');
    if (!rows) return;
    rows.innerHTML = state.students.map(student => {
      const complete = Boolean(student.guardian_connected);
      const status = student.status === 'active' ? 'Aktif' : student.status || 'Belum aktif';
      return `<tr data-status="${safe(student.status)}"><td><div class="student-cell"><span class="payer-avatar">${safe(initials(student.full_name))}</span><span class="student-detail">${safe(student.full_name)}<small>${safe(student.nis || student.id)}</small></span></div></td><td>${safe(student.class_name || 'Belum ditempatkan')}</td><td>${safe(student.guardian_name || 'Belum dihubungkan')}</td><td><span class="status-pill${student.status === 'active' ? '' : ' pending'}">${safe(status)}</span></td><td><span class="status-pill${complete ? '' : ' pending'}">${complete ? 'Lengkap' : 'Kurang'}</span></td><td><button class="row-action" type="button" data-live-student="${safe(student.id)}">Detail</button></td></tr>`;
    }).join('') || '<tr><td colspan="6">Belum ada data santri.</td></tr>';
    const total = state.students.length;
    const active = state.students.filter(item => item.status === 'active').length;
    const linked = state.students.filter(item => item.guardian_connected).length;
    document.getElementById('studentTotal')?.replaceChildren(document.createTextNode(String(total)));
    document.getElementById('activeTotal')?.replaceChildren(document.createTextNode(String(active)));
    document.getElementById('guardianTotal')?.replaceChildren(document.createTextNode(String(linked)));
    const activeFoot = document.getElementById('activeFoot'); if (activeFoot) activeFoot.textContent = `${total ? ((active / total) * 100).toFixed(1).replace('.', ',') : '0'}% dari total`;
     const guardianFoot = document.getElementById('guardianFoot'); if (guardianFoot) guardianFoot.textContent = `${total - linked} perlu dilengkapi`;
     const chip = document.getElementById('studentChip'); if (chip) chip.textContent = `${total} santri`;
     setText('documentTotal', String(total - linked).padStart(2, '0'));
     markLive('#studentChip');
  }

  async function loadStaff() {
    const response = await api('admin/staff'); state.staff = response.items || [];
    const select = document.getElementById('staffUnit');
    if (select && institutions().length) select.innerHTML = institutions().map(item => `<option value="${safe(item.id)}">${safe(item.name)}</option>`).join('');
    renderStaff();
  }
  function renderStaff() {
    const rows = document.getElementById('staffRows'); if (!rows) return;
    rows.innerHTML = state.staff.map(item => `<tr data-staff="${safe(item.employment_type || 'fixed')}"><td><div class="teacher-cell"><span class="teacher-avatar">${safe(initials(item.display_name))}</span><span class="teacher-detail">${safe(item.display_name)}<small>${safe(item.institution_name || '')}</small></span></div></td><td><span class="qualification">${safe(item.education || 'Belum diisi')}<small>${safe(item.subject || item.role_title || '')}</small></span></td><td><span class="employment">${item.employment_type === 'honor' ? 'Honorer' : 'Tetap'}</span></td><td class="jtm-number">${Number(item.weekly_hours) || 0} jam</td><td class="attendance-good">—</td><td><button class="row-action" type="button" data-live-staff="${safe(item.id)}">Detail</button></td></tr>`).join('') || '<tr><td colspan="6">Belum ada data guru.</td></tr>';
    const active = state.staff.filter(item => item.status === 'active').length;
    const hours = state.staff.reduce((sum, item) => sum + (Number(item.weekly_hours) || 0), 0);
     const values = document.querySelectorAll('.metrics-grid .metric-value'); if (values[0]) values[0].textContent = String(active); if (document.getElementById('jtmMetric')) document.getElementById('jtmMetric').textContent = String(hours);
     const chip = document.querySelector('#staffHeading')?.closest('.panel')?.querySelector('.data-chip'); if (chip) chip.textContent = `${active} guru aktif`;
     markLive('#staffHeading + .data-chip');
  }

  async function loadTahfidz() {
    await records('tahfidz');
    const list = document.getElementById('student-list'); if (!list) return;
    const latest = new Map(); (state.records.tahfidz || []).forEach(item => { if (!latest.has(item.entity_id)) latest.set(item.entity_id, item.payload || {}); });
    const activeClassId = portal()?.primaryClass?.id; const visibleStudents = state.students.filter(student => !activeClassId || !student.class_id || student.class_id === activeClassId);
    list.innerHTML = visibleStudents.map(student => { const item = latest.get(student.id) || {}; const stage = item.stage || 'setoran'; const progress = Math.max(0, Math.min(100, Number(item.progress) || 0)); return `<article class="student-card" data-name="${safe(student.full_name.toLowerCase())}" data-stage="${safe(stage)}" data-student="${safe(student.full_name)}" data-student-id="${safe(student.id)}"><span class="student-avatar">${safe(initials(student.full_name))}</span><span><strong class="student-name">${safe(student.full_name)}</strong><span class="student-sub">${safe(item.kind || 'Tahfidz')} · ${safe(item.target || 'Belum ada setoran')}</span><span class="stage-chip${stage === 'murojaah' ? ' warn' : ''}">${stage === 'murojaah' ? 'Perlu murojaah' : 'Siap dicatat'}</span></span><span class="progress-copy"><span class="progress-line"><span>Progres</span><strong>${progress}%</strong></span><span class="track"><span class="fill" style="width:${progress}%"></span></span></span><button class="student-action" type="button" data-live-record-student="${safe(student.id)}">Catat <span>→</span></button></article>`; }).join('');
    const select = document.getElementById('record-student'); if (select) select.innerHTML = visibleStudents.map(student => `<option value="${safe(student.id)}">${safe(student.full_name)}</option>`).join('');
    const review = (state.records.tahfidz || []).filter(item => item.payload?.stage === 'murojaah').length; const reviewNode = document.getElementById('review-count'); if (reviewNode) reviewNode.textContent = String(review).padStart(2, '0');
    const weekStart = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = (state.records.tahfidz || []).filter(item => new Date(item.updated_at || item.created_at).getTime() >= weekStart);
    const progressValues = [...latest.values()].map(item => Number(item.progress)).filter(value => Number.isFinite(value));
    const metrics = document.querySelectorAll('.metrics-grid .metric-value');
    if (metrics[0]) metrics[0].textContent = String(state.students.filter(item => item.status === 'active').length);
    if (metrics[1]) metrics[1].textContent = String(recent.length);
    if (metrics[3]) metrics[3].textContent = `${progressValues.length ? Math.round(progressValues.reduce((sum, value) => sum + value, 0) / progressValues.length) : 0}%`;
    markLiveNode(document.querySelector('#progress-title')?.closest('.panel')?.querySelector('.data-chip'));
    const query = document.getElementById('student-search')?.value.trim().toLowerCase() || ''; list.querySelectorAll('.student-card').forEach(card => { card.hidden = Boolean(query) && !card.dataset.name.includes(query); });
  }
  async function loadGrades() {
    await records('grades');
    const classSelect = document.getElementById('class-select'); if (classSelect && state.classes.length) classSelect.innerHTML = state.classes.map(item => `<option value="${safe(item.id)}">${safe(item.name || item.code)} · ${safe(item.institution_code || '')}</option>`).join('');
    renderGrades();
  }
  function gradeKey(studentId) { return `grades:${studentId}:${document.getElementById('class-select')?.value || 'all'}:${document.getElementById('term-select')?.value || 'term-1'}`; }
  function renderGrades() {
    const rows = document.getElementById('grade-rows'); if (!rows) return;
    const map = new Map((state.records.grades || []).map(item => [item.record_key, item]));
     const selectedClassId = document.getElementById('class-select')?.value; const visibleStudents = state.students.filter(student => !selectedClassId || !student.class_id || student.class_id === selectedClassId); rows.innerHTML = visibleStudents.map(student => { const item = map.get(gradeKey(student.id)); const scores = item?.payload?.scores || {}; const subjects = ['tahsin', 'tahfidz', 'adab']; const entered = subjects.filter(subject => scores[subject] !== undefined && scores[subject] !== null && scores[subject] !== ''); const needs = entered.some(subject => Number(scores[subject]) < 75); const average = entered.length ? `${Math.round(entered.reduce((sum, subject) => sum + Number(scores[subject]), 0) / entered.length)}%` : '—'; const status = !entered.length ? 'Belum dinilai' : needs ? 'Perlu perhatian' : 'Tuntas'; return `<tr data-student-id="${safe(student.id)}" data-needs="${needs}"><td><div class="student-cell"><span class="student-avatar">${safe(initials(student.full_name))}</span><span class="student-detail">${safe(student.full_name)}<small>${safe(student.class_name || '')}</small></span></div></td>${subjects.map(subject => `<td><input class="score-input${Number(scores[subject]) < 75 ? ' low' : ''}" type="number" min="0" max="100" value="${scores[subject] ?? ''}" data-grade-subject="${subject}" data-student-id="${safe(student.id)}" /></td>`).join('')}<td>${average}</td><td><span class="status-pill${needs ? ' needs-review' : ''}">${status}</span></td><td><button class="note-button" type="button" data-live-note="${safe(student.id)}">…</button></td></tr>`; }).join('');
     const inputs = [...document.querySelectorAll('[data-grade-subject]')]; const entered = inputs.filter(input => input.value !== ''); const passed = entered.filter(input => Number(input.value) >= 75).length; if (document.getElementById('saved-count')) document.getElementById('saved-count').textContent = String(entered.length); if (document.getElementById('kkm-rate')) document.getElementById('kkm-rate').textContent = `${entered.length ? Math.round((passed / entered.length) * 100) : 0}%`; setText('ready-count', String([...document.querySelectorAll('#grade-rows tr[data-needs="false"]')].filter(row => [...row.querySelectorAll('[data-grade-subject]')].every(input => input.value !== '')).length).padStart(2, '0')); const previewStudent = visibleStudents[0]; const previewItem = previewStudent && map.get(gradeKey(previewStudent.id)); const previewScores = previewItem?.payload?.scores || {}; const previewValues = ['tahsin', 'tahfidz', 'adab'].map(subject => Number(previewScores[subject])).filter(Number.isFinite); const previewAverage = previewValues.length ? (previewValues.reduce((sum, value) => sum + value, 0) / previewValues.length).toFixed(1).replace('.', ',') : '—'; const previewName = previewStudent?.full_name || 'Belum ada santri'; document.querySelector('.report-preview h3')?.replaceChildren(document.createTextNode(previewName)); document.querySelector('.sheet-head strong')?.replaceChildren(document.createTextNode(previewName)); setText('reportScore', previewAverage); setText('reportModalScore', previewAverage); const reportStatus = previewItem?.payload?.approval_status === 'pending' ? 'Menunggu persetujuan kepala lembaga' : previewItem?.payload?.approval_status === 'approved' ? 'Sudah disetujui' : 'Belum diajukan ke kepala lembaga'; setText('approval-status', reportStatus); const reportChip = document.querySelector('.report-panel .data-chip'); if (reportChip) reportChip.textContent = previewItem?.payload?.approval_status === 'pending' ? 'MENUNGGU' : 'DRAFT'; markLiveNode(document.querySelector('#gradebook-title')?.closest('.panel')?.querySelector('.data-chip'));
  }

  async function loadFinance() {
    await records('finance'); renderFinance();
  }
  function renderFinance() {
    const items = state.records.finance || [], invoices = items.filter(item => item.payload?.type === 'invoice'), transactions = items.filter(item => item.payload?.type !== 'invoice');
    const bills = document.getElementById('billRows'); if (bills) bills.innerHTML = invoices.map(item => { const p = item.payload || {}; const overdueByDate = p.status === 'pending' && p.due_date && new Date(`${p.due_date}T23:59:59`) < new Date(); const status = overdueByDate ? 'overdue' : p.status || 'pending'; return `<tr data-status="${safe(status)}"><td><div class="payer-cell"><span class="payer-avatar">${safe(initials(p.student_name || p.payer_name))}</span><span class="payer-detail">${safe(p.student_name || 'Santri')}<small>Wali: ${safe(p.guardian_name || 'Belum dihubungkan')}</small></span></div></td><td>${safe(fmtDate(p.due_date))}</td><td class="amount">${safe(fmtMoney(p.amount))}</td><td><span class="status-pill${status === 'paid' ? '' : ' pending'}">${status === 'paid' ? 'Lunas' : status === 'overdue' ? 'Terlambat' : 'Menunggu'}</span></td><td><button class="pay-button" type="button" data-live-finance="${safe(item.id)}" data-action="${status === 'paid' ? 'receipt' : 'remind'}">${status === 'paid' ? 'Kwitansi' : 'Ingatkan'}</button></td></tr>`; }).join('') || '<tr><td colspan="5">Belum ada tagihan tersimpan.</td></tr>';
    const table = document.querySelectorAll('.bill-table')[1]; if (table) table.querySelector('tbody').innerHTML = transactions.map(item => { const p = item.payload || {}; return `<tr><td><div class="payer-cell"><span class="payer-avatar">${safe(initials(p.payer_name || p.program))}</span><span class="payer-detail">${safe(p.description || p.program || 'Transaksi')}<small>${safe(item.record_key)}</small></span></div></td><td>${safe(fmtDate(item.created_at))}</td><td>${safe(p.method || 'Manual')}</td><td class="amount">+ ${safe(fmtMoney(p.amount))}</td><td><span class="status-pill">Tercatat</span></td></tr>`; }).join('') || '<tr><td colspan="5">Belum ada transaksi.</td></tr>';
    const income = transactions.reduce((sum, item) => sum + (Number(item.payload?.amount) || 0), 0); const billed = invoices.reduce((sum, item) => sum + (Number(item.payload?.amount) || 0), 0); const overdue = invoices.filter(item => item.payload?.status === 'overdue' || (item.payload?.status === 'pending' && item.payload?.due_date && new Date(`${item.payload.due_date}T23:59:59`) < new Date())).length; const donations = transactions.filter(item => item.payload?.type === 'donation'); const donation = donations.reduce((sum, item) => sum + (Number(item.payload?.amount) || 0), 0);
    setText('incomeValue', fmtMoney(income)); setText('billedValue', fmtMoney(billed)); setText('overdueValue', String(overdue)); setText('donationValue', fmtMoney(donation));
    const programs = [...new Set(donations.map(item => item.payload?.program).filter(Boolean))]; const donationChip = document.querySelector('.donation-card .data-chip'); if (donationChip) donationChip.textContent = `${programs.length} program`; const donationTotal = document.querySelector('.donation-card .donation-copy em'); if (donationTotal) donationTotal.textContent = `${fmtMoney(donation)} terkumpul`; const cashTotal = document.querySelector('.cash-total strong'); if (cashTotal) cashTotal.textContent = fmtMoney(income); markLiveNode(document.querySelector('#sppHeading')?.closest('.panel')?.querySelector('.data-chip'));
  }

  async function loadCms() {
    const response = await api('admin/content'); state.content = response.items || []; await records('media');
    const rows = document.getElementById('contentRows'); if (!rows) return;
    rows.innerHTML = state.content.map((item, index) => `<tr data-content="${safe(item.status)}"><td><div class="article-cell"><span class="article-thumb">${String(index + 1).padStart(2, '0')}</span><span class="article-copy">${safe(item.title)}<small>${safe(fmtDate(item.updated_at))}</small></span></div></td><td><span class="type-label">${safe(item.content_type)}</span></td><td>${safe(item.institution_name || 'Yayasan')}</td><td><span class="publish-pill${item.status === 'draft' ? ' draft' : ''}">${item.status === 'published' ? 'Tayang' : item.status === 'archived' ? 'Arsip' : 'Draft'}</span></td><td><button class="row-action" type="button" data-live-content="${safe(item.id)}">Edit</button></td></tr>`).join('') || '<tr><td colspan="5">Belum ada konten.</td></tr>';
    const scheduled = state.content.filter(item => item.status === 'draft' && item.published_at).length; const published = state.content.filter(item => item.status === 'published').length; const metrics = document.querySelectorAll('.metrics-grid .metric-value'); if (metrics[0]) metrics[0].textContent = String(state.content.length); if (metrics[1]) metrics[1].textContent = String(published); setText('scheduledValue', String(scheduled).padStart(2, '0')); if (metrics[3]) metrics[3].textContent = String((state.records.media || []).length);
    const chip = document.querySelector('#libraryHeading')?.closest('.panel')?.querySelector('.data-chip'); if (chip) chip.textContent = `${state.content.length} konten`;
    const mediaGrid = document.querySelector('.media-grid'); if (mediaGrid) mediaGrid.innerHTML = (state.records.media || []).map(item => { const p = item.payload || {}; return `<div class="media-item"><span>${safe(p.category || 'Media kegiatan')}<small>${safe(p.filename || 'File tersimpan')} · ${safe(fmtDate(item.created_at))}</small></span></div>`; }).join('') || '<p>Belum ada media tersimpan.</p>';
    const pageList = document.querySelector('.page-list'); const pages = state.content.filter(item => item.content_type === 'page'); if (pageList && pages.length) pageList.innerHTML = pages.map(item => `<div class="page-item"><span class="page-mark">▤</span><span class="page-copy"><strong>${safe(item.title)}</strong><span>Diperbarui ${safe(fmtDate(item.updated_at))}</span></span><button class="page-edit" type="button" data-live-content="${safe(item.id)}">Edit</button></div>`).join('');
    const bannerList = document.querySelector('.banner-list'); const banners = state.content.filter(item => item.content_type === 'banner'); if (bannerList && banners.length) bannerList.innerHTML = banners.map((item, index) => `<div class="banner-row"><span class="banner-preview">${String(index + 1).padStart(2, '0')}</span><span class="banner-copy"><strong>${safe(item.title)}</strong><span>Urutan ${index + 1} · ${item.status === 'published' ? 'tampil di beranda' : 'draft'}</span></span><button class="banner-toggle${item.status !== 'published' ? ' off' : ''}" type="button" data-live-banner="${safe(item.id)}">${item.status === 'published' ? 'Aktif' : 'Nonaktif'}</button></div>`).join('');
    markLiveNode(document.querySelector('#libraryHeading')?.closest('.panel')?.querySelector('.data-chip'));
  }
  const periodLabel = period => { if (!period) return ''; const date = new Date(`${period}-01T00:00:00`); return Number.isNaN(date.getTime()) ? period : new Intl.DateTimeFormat('id-ID', { month: 'short' }).format(date); };
  function renderAnalyticsVisuals(summary) {
    const registration = summary.registration_trend || []; const plot = document.querySelector('.plot-columns'); const axis = document.querySelector('.plot-area .x-axis'); const max = Math.max(1, ...registration.map(item => Number(item.total) || 0));
    if (plot) plot.innerHTML = registration.map(item => `<div class="plot-column"><i class="plot-bar" style="height:${Math.round(((Number(item.total) || 0) / max) * 100)}%"></i><i class="plot-bar alt" style="height:${Math.round(((Number(item.pending) || 0) / max) * 100)}%"></i></div>`).join('') || '<span>Belum ada data pendaftaran.</span>'; if (axis) axis.innerHTML = registration.map(item => `<span>${safe(periodLabel(item.period))}</span>`).join('');
    const attendance = summary.attendance_trend || []; const points = document.querySelector('.mini-line-chart'); const labels = document.querySelector('.line-labels'); const rates = attendance.map(item => ({ ...item, rate: Number(item.total) ? (Number(item.attended || 0) / Number(item.total)) * 100 : 0 }));
    if (points) points.innerHTML = rates.map(item => `<i class="line-point" style="height:${Math.max(2, Math.round(item.rate))}%"></i>`).join('') || '<span>Belum ada data kehadiran.</span>'; if (labels) labels.innerHTML = rates.map(item => `<span>${safe(periodLabel(item.period))}</span>`).join(''); const latestRate = rates.at(-1)?.rate; if (latestRate !== undefined) { setText('attendanceTotal', `${latestRate.toFixed(1).replace('.', ',')}%`); setText('attendanceChartValue', `${latestRate.toFixed(1).replace('.', ',')}%`); }
  }
  async function loadNotifications() {
    await records('notifications'); await records('calendar'); await records('settings');
    const rows = document.getElementById('deliveryRows'); if (!rows) return;
    rows.innerHTML = (state.records.notifications || []).map(item => { const p = item.payload || {}; const delivery = p.status || 'sent'; return `<tr data-delivery="${safe(delivery)}"><td><div class="message-cell"><span class="message-icon">${p.channel === 'email' ? '@' : 'WA'}</span><span class="message-detail">${safe(p.title || 'Pesan')}<small>${safe(p.target || 'Penerima')} · ${safe(p.mode || 'Manual')}</small></span></div></td><td>${safe(p.target || '—')}</td><td>${safe(fmtDate(item.created_at))}</td><td>${safe(p.read_rate || '—')}</td><td><span class="delivery-status${delivery === 'scheduled' ? ' scheduled' : ''}">${delivery === 'scheduled' ? 'Terjadwal' : delivery === 'failed' ? 'Gagal' : 'Berhasil'}</span></td></tr>`; }).join('') || '<tr><td colspan="5">Belum ada riwayat pengiriman.</td></tr>';
    const sent = (state.records.notifications || []).filter(item => item.payload?.status !== 'scheduled' && item.payload?.status !== 'failed').length; const failed = (state.records.notifications || []).filter(item => item.payload?.status === 'failed').length; const sentNode = document.getElementById('sentValue'); if (sentNode) sentNode.textContent = String(sent); setText('failedValue', failed); const rules = new Map((state.records.settings || []).filter(item => item.payload?.type === 'notification_rule').map(item => [item.payload.name || item.record_key, item.payload.enabled])); document.querySelectorAll('[data-rule]').forEach(button => { const key = button.dataset.rule || button.textContent.trim(); if (rules.has(key)) button.classList.toggle('on', Boolean(rules.get(key))); }); const ruleNode = document.getElementById('ruleValue'); if (ruleNode) ruleNode.textContent = String([...rules.values()].filter(Boolean).length).padStart(2, '0');
    const calendar = document.querySelector('.calendar-list'); if (calendar) calendar.innerHTML = (state.records.calendar || []).map(item => { const p = item.payload || {}; const date = p.date ? new Date(`${p.date}T00:00:00`) : null; return `<div class="calendar-item"><span class="calendar-date"><strong>${date ? String(date.getDate()).padStart(2, '0') : '—'}</strong><span>${date ? new Intl.DateTimeFormat('id-ID', { month: 'short' }).format(date) : ''}</span></span><span class="calendar-copy"><strong>${safe(p.title || 'Acara')}</strong><span>${safe(p.location || 'Kalender akademik')}</span></span></div>`; }).join('') || '<p>Belum ada acara terjadwal.</p>';
    markLiveNode(document.querySelector('#deliveryHeading')?.closest('.panel')?.querySelector('.data-chip'));
  }
  async function loadAnalytics() {
    const summary = await api('admin/summary'); state.summary = summary; const studentResponse = await api('admin/students'); state.students = studentResponse.items || [];
    const set = (id, value) => { const node = document.getElementById(id); if (node) node.textContent = value; };
    set('studentTotal', summary.students_active ?? 0); set('admissionTotal', summary.registrations_pending ?? 0);
    const finance = await records('finance'); const income = (finance || []).filter(item => item.payload?.type !== 'invoice').reduce((sum, item) => sum + (Number(item.payload?.amount) || 0), 0); set('incomeTotal', fmtMoney(income));
    const attendance = summary.attendance_sessions_today ? 'Ada sesi' : '0 sesi'; set('attendanceTotal', attendance); set('attendanceChartValue', attendance); renderAnalyticsVisuals(summary);
    const scope = document.getElementById('scopeSelect'); if (scope) { scope.innerHTML = '<option value="all">Seluruh yayasan</option>' + institutions().map(item => `<option value="${safe(item.id)}">${safe(item.name)}</option>`).join(''); }
    const groups = (summary.institution_breakdown || []).map(item => ({ name: item.name, count: Number(item.active_students) || 0 })).sort((a, b) => b.count - a.count); const fallbackGroups = [...state.students.reduce((map, item) => { const key = item.institution_id || item.institution_name || 'unknown'; const group = map.get(key) || { name: item.institution_name || 'Lembaga belum ditentukan', count: 0 }; group.count += item.status === 'active' ? 1 : 0; map.set(key, group); return map; }, new Map()).values()].sort((a, b) => b.count - a.count); const institutionGroups = groups.length ? groups : fallbackGroups; const institutionList = document.querySelector('.institution-list'); if (institutionList) institutionList.innerHTML = institutionGroups.map(group => `<div class="institution-row"><div class="institution-copy"><span class="institution-mark">${safe(initials(group.name))}</span><span><strong>${safe(group.name)}</strong><span>Santri aktif</span></span></div><b class="institution-total">${group.count}</b><div class="bar-line"><i style="width:${institutionGroups[0]?.count ? Math.round((group.count / institutionGroups[0].count) * 100) : 0}%"></i></div></div>`).join('') || '<p>Belum ada data sebaran santri.</p>'; markLiveNode(document.querySelector('#institutionHeading')?.closest('.institution-card')?.querySelector('.data-chip')); markLiveNode(document.querySelector('#admissionHeading')?.closest('.panel')?.querySelector('.data-chip'));
  }
  async function loadSettingsPage() {
    await records('alumni');
    const list = document.querySelector('.alumni-list'); if (!list) return;
    list.innerHTML = (state.records.alumni || []).map(item => { const p = item.payload || {}; return `<article class="alumni-card"><div class="alumni-top"><span class="alumni-avatar">${safe(initials(p.name))}</span><span><strong>${safe(p.name)}</strong><small>Angkatan ${safe(p.year)} · ${safe(p.unit)}</small></span></div><span class="alumni-note">${safe(p.note || 'Profil alumni tersimpan di direktori.')}</span><span class="alumni-action">Profil tersimpan</span></article>`; }).join('') || '<p>Belum ada profil alumni.</p>';
  }
  async function exportModule(module, name, rows) {
    try { const data = rows || (await records(module)); download(name, csv(data.map(item => [item.id, item.record_key, JSON.stringify(item.payload), item.status, item.updated_at]))); toast('Ekspor selesai', 'File rekap berhasil diunduh.'); } catch (error) { toast('Ekspor gagal', error.message); }
  }
  async function saveGrade(input) {
    const row = input.closest('tr'); const studentId = input.dataset.studentId; const scores = {}; row.querySelectorAll('[data-grade-subject]').forEach(item => { scores[item.dataset.gradeSubject] = item.value === '' ? null : Number(item.value); });
    try { const saved = await saveRecord('grades', gradeKey(studentId), { scores, approval_status: 'draft' }, studentId); const existing = state.records.grades.findIndex(item => item.record_key === saved.record_key); if (existing >= 0) state.records.grades[existing] = saved; else state.records.grades.unshift(saved); input.classList.toggle('low', Number(input.value) < 75); toast('Nilai tersimpan', 'Perubahan sudah tersimpan ke server.'); renderGrades(); } catch (error) { toast('Nilai belum tersimpan', error.message); }
  }
  async function handleSubmit(event) {
    const form = event.target; if (!(form instanceof HTMLFormElement)) return;
    if (form.id === 'studentForm') { event.preventDefault(); event.stopImmediatePropagation(); const payload = { full_name: document.getElementById('studentName').value.trim(), nis: document.getElementById('studentNis').value.trim() || null, status: 'active', class_id: document.querySelector('#studentClass')?.value || null, guardian_name: document.getElementById('studentGuardian').value.trim() || null }; try { await api('admin/students', json('POST', payload)); closeModal('studentModal'); await loadStudents(); toast('Santri tersimpan', 'Data induk sudah masuk ke server.'); } catch (error) { toast('Santri belum tersimpan', error.message); } return; }
    if (form.id === 'staffForm') { event.preventDefault(); event.stopImmediatePropagation(); const payload = { display_name: document.getElementById('staffName').value.trim(), education: document.getElementById('staffQualification').value.trim(), employment_type: document.getElementById('staffStatus').value, institution_id: document.getElementById('staffUnit').value, weekly_hours: Number(document.getElementById('staffJtm').value) || 0, status: 'active' }; try { await api('admin/staff', json('POST', payload)); closeModal('staffModal'); await loadStaff(); toast('Guru tersimpan', 'Data kepegawaian sudah masuk ke server.'); } catch (error) { toast('Guru belum tersimpan', error.message); } return; }
    if (form.id === 'record-form') { event.preventDefault(); event.stopImmediatePropagation(); const studentId = document.getElementById('record-student').value; const score = document.querySelector('[data-score].active')?.dataset.score || 'lancar'; const payload = { kind: document.querySelector('[data-kind].active')?.dataset.kind === 'tahsin' ? 'Tahsin' : 'Tahfidz', target: document.getElementById('record-target').value.trim(), score, stage: ['bimbingan', 'ulang'].includes(score) ? 'murojaah' : 'setoran', note: document.getElementById('record-note').value.trim(), progress: 0, recorded_at: new Date().toISOString() }; try { await saveRecord('tahfidz', `${studentId}:${Date.now()}`, payload, studentId); await loadTahfidz(); toast('Capaian tersimpan', 'Setoran sudah tercatat di server.'); } catch (error) { toast('Capaian belum tersimpan', error.message); } return; }
    if (form.id === 'invoiceForm' || form.id === 'donationForm') { event.preventDefault(); event.stopImmediatePropagation(); const invoice = form.id === 'invoiceForm'; const payload = invoice ? { type: 'invoice', student_name: document.getElementById('studentName').value.trim(), amount: Number(document.getElementById('invoiceAmount').value), due_date: document.getElementById('invoiceDue').value, category: document.getElementById('invoiceType').value, status: 'pending' } : { type: 'donation', payer_name: document.getElementById('donorName').value.trim(), amount: Number(document.getElementById('donationAmount').value), program: document.getElementById('donationProgram').value, description: `Donasi ${document.getElementById('donationProgram').value}`, method: 'Manual' }; try { await saveRecord('finance', `${payload.type}:${Date.now()}`, payload); closeModal(invoice ? 'invoiceModal' : 'donationModal'); await loadFinance(); toast(invoice ? 'Tagihan tersimpan' : 'Donasi tersimpan', 'Catatan keuangan sudah tersimpan.'); } catch (error) { toast('Transaksi belum tersimpan', error.message); } return; }
    if (form.id === 'articleForm') { event.preventDefault(); event.stopImmediatePropagation(); const status = document.getElementById('articlePublish').value === 'publish' ? 'published' : 'draft'; const payload = { site_kind: 'foundation', content_type: document.getElementById('articleType').value, slug: document.getElementById('articleName').value.trim().toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''), title: document.getElementById('articleName').value.trim(), body: document.getElementById('articleCopy').value.trim(), status }; try { if (state.editingContent) await api(`admin/content/${state.editingContent}`, json('PUT', payload)); else await api('admin/content', json('POST', payload)); state.editingContent = null; closeModal('articleModal'); await loadCms(); toast('Konten tersimpan', 'Konten publik sudah tersimpan sebagai draft atau tayang.'); } catch (error) { toast('Konten belum tersimpan', error.message); } return; }
    if (form.id === 'mediaForm') { event.preventDefault(); event.stopImmediatePropagation(); const file = document.getElementById('mediaFile').files[0]; const payload = { type: 'media', filename: file?.name || '', category: document.getElementById('mediaCategory').value.trim(), size: file?.size || 0 }; try { let fileUrl = ''; const p = portal(); if (file && p?.client?.storage) { const path = `${p.context?.profile?.tenant_id || 'tenant'}/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const upload = await p.client.storage.from('site-media').upload(path, file, { upsert: false }); if (upload.error) throw upload.error; fileUrl = p.client.storage.from('site-media').getPublicUrl(path).data.publicUrl; } await saveRecord('media', `media:${Date.now()}`, { ...payload, file_url: fileUrl }); closeModal('mediaModal'); toast('Media tersimpan', 'File media dan metadata sudah tersimpan.'); } catch (error) { toast('Media belum tersimpan', error.message); } return; }
    if (form.id === 'pageForm' || form.id === 'bannerForm') { event.preventDefault(); event.stopImmediatePropagation(); const pageForm = form.id === 'pageForm'; const title = document.getElementById(pageForm ? 'pageName' : 'bannerName').value.trim(); const body = pageForm ? document.getElementById('pageCopy').value.trim() : ''; const slug = title.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, ''); const payload = { site_kind: 'foundation', content_type: pageForm ? 'page' : 'banner', slug, title, body, excerpt: pageForm ? '' : document.getElementById('bannerCta').value.trim(), status: pageForm || document.getElementById('bannerStatus').value === 'Aktif' ? 'published' : 'draft' }; try { if (pageForm && state.editingContent) await api(`admin/content/${state.editingContent}`, json('PUT', payload)); else await api('admin/content', json('POST', payload)); state.editingContent = null; closeModal(pageForm ? 'pageModal' : 'bannerModal'); await loadCms(); toast('Konten tersimpan', 'Perubahan CMS sudah masuk ke database.'); } catch (error) { toast('Konten belum tersimpan', error.message); } return; }
    if (form.id === 'broadcastForm') { event.preventDefault(); event.stopImmediatePropagation(); const target = document.getElementById('broadcastTarget')?.selectedOptions[0]?.text || 'Penerima'; const channel = document.querySelector('[data-channel].active')?.dataset.channel === 'email' ? 'Email' : 'WhatsApp'; setText('previewChannel', `${channel} · ${target.split('·')[1]?.trim() || 'penerima'}`); setText('previewSubject', document.getElementById('broadcastTitle')?.value.trim() || 'Broadcast'); setText('previewCopy', document.getElementById('broadcastMessage')?.value.trim() || ''); const confirm = document.getElementById('confirmBroadcast'); if (confirm) confirm.textContent = document.getElementById('sendMode')?.value === 'now' ? 'Kirim pesan' : 'Jadwalkan pesan'; openModal('previewModal'); return; }
    if (form.id === 'calendarForm') { event.preventDefault(); event.stopImmediatePropagation(); const payload = { type: 'calendar', title: document.getElementById('eventName').value.trim(), date: document.getElementById('eventDate').value }; try { await saveRecord('calendar', `calendar:${Date.now()}`, payload); closeModal('calendarModal'); toast('Acara tersimpan', 'Acara kalender sudah tersimpan.'); } catch (error) { toast('Acara belum tersimpan', error.message); } }
    if (form.id === 'alumniForm') { event.preventDefault(); event.stopImmediatePropagation(); const payload = { type: 'alumni', name: document.getElementById('alumniName').value.trim(), year: document.getElementById('alumniYear').value, unit: document.getElementById('alumniUnit').value, note: document.getElementById('alumniNote').value.trim() }; try { await saveRecord('alumni', `alumni:${Date.now()}`, payload); closeModal('alumniModal'); toast('Alumni tersimpan', 'Profil alumni sudah masuk direktori.'); } catch (error) { toast('Alumni belum tersimpan', error.message); } }
  }
  async function handleClick(event) {
    const target = event.target.closest('button, [role="button"]'); if (!target) return;
    if (target.dataset.filter || target.dataset.staffFilter || target.dataset.contentFilter || target.dataset.deliveryFilter || target.dataset.stage) {
      event.preventDefault(); event.stopImmediatePropagation();
      const group = target.closest('.filter-tabs, .progress-tools'); group?.querySelectorAll('button').forEach(button => button.classList.toggle('active', button === target));
      if (target.dataset.filter) {
        const filter = target.dataset.filter;
        if (page === 'absensi.html') document.querySelectorAll('#student-rows tr[data-attendance-student], #student-rows tr[data-name]').forEach(row => { row.hidden = filter !== 'all' && (filter === 'izin' ? !['izin', 'sakit'].includes(row.dataset.status) : row.dataset.status !== filter); });
        if (page === 'santri.html') document.querySelectorAll('#studentRows tr').forEach(row => { row.hidden = filter !== 'all' && (filter === 'pending' ? row.dataset.status === 'active' : row.dataset.status !== filter); });
        if (page === 'keuangan.html') document.querySelectorAll('#billRows tr').forEach(row => { row.hidden = filter !== 'all' && row.dataset.status !== filter; });
      }
      if (target.dataset.staffFilter) document.querySelectorAll('#staffRows tr').forEach(row => { row.hidden = target.dataset.staffFilter !== 'all' && row.dataset.staff !== target.dataset.staffFilter; });
      if (target.dataset.contentFilter) document.querySelectorAll('#contentRows tr').forEach(row => { row.hidden = target.dataset.contentFilter !== 'all' && row.dataset.content !== target.dataset.contentFilter; });
      if (target.dataset.deliveryFilter) document.querySelectorAll('#deliveryRows tr').forEach(row => { row.hidden = target.dataset.deliveryFilter !== 'all' && row.dataset.delivery !== target.dataset.deliveryFilter; });
      if (target.dataset.stage) document.querySelectorAll('#student-list .student-card').forEach(card => { card.hidden = target.dataset.stage !== 'all' && card.dataset.stage !== target.dataset.stage; });
      return;
    }
    if (target.matches('[data-live-record-student]')) { event.preventDefault(); event.stopImmediatePropagation(); const select = document.getElementById('record-student'); if (select) select.value = target.dataset.liveRecordStudent; document.getElementById('record-panel')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); return; }
    if (target.matches('[data-live-student]')) { event.preventDefault(); event.stopImmediatePropagation(); const student = state.students.find(item => item.id === target.dataset.liveStudent); if (student) toast(student.full_name, `${student.class_name || 'Kelas belum ditentukan'} · ${student.guardian_name || 'Wali belum terhubung'} · ${student.status || 'status belum diisi'}`); return; }
    if (target.matches('[data-live-staff]')) { event.preventDefault(); event.stopImmediatePropagation(); const staff = state.staff.find(item => item.id === target.dataset.liveStaff); if (staff) toast(staff.display_name, `${staff.institution_name || 'Lembaga belum ditentukan'} · ${staff.subject || staff.role_title || 'Pengajar'} · ${staff.weekly_hours || 0} jam per minggu`); return; }
    if (target.matches('[data-live-attendance]')) { event.preventDefault(); event.stopImmediatePropagation(); const row = target.closest('tr'); toast(row?.querySelector('.student-detail')?.textContent.trim() || 'Detail absensi', `Status hari ini: ${row?.dataset.status || 'belum diisi'}.`); return; }
    if (target.dataset.page && page === 'cms.html') { event.preventDefault(); event.stopImmediatePropagation(); const item = state.content.find(content => content.title === target.dataset.page); state.editingContent = item?.id || null; document.getElementById('pageName').value = item?.title || target.dataset.page; document.getElementById('pageCopy').value = item?.body || ''; openModal('pageModal'); return; }
    if (target.dataset.edit && page === 'cms.html') { event.preventDefault(); event.stopImmediatePropagation(); const item = state.content.find(content => content.title === target.dataset.edit); state.editingContent = item?.id || null; document.getElementById('articleName').value = item?.title || target.dataset.edit; document.getElementById('articleCopy').value = item?.body || ''; const typeSelect = document.getElementById('articleType'); typeSelect.value = [...typeSelect.options].some(option => option.value === item?.content_type) ? item.content_type : 'Artikel'; document.getElementById('articlePublish').value = item?.status === 'published' ? 'publish' : 'draft'; openModal('articleModal'); return; }
    if (target.matches('[data-live-finance]')) { event.preventDefault(); event.stopImmediatePropagation(); const item = (state.records.finance || []).find(record => record.id === target.dataset.liveFinance); if (!item) return; const p = item.payload || {}; if (target.dataset.action === 'remind') { try { await api(`admin/records/${item.id}`, json('PUT', { payload: { ...p, reminded_at: new Date().toISOString() } })); toast('Pengingat tercatat', 'Status tindak lanjut sudah disimpan.'); } catch (error) { toast('Pengingat gagal', error.message); } } else { download(`kwitansi-${item.record_key}.csv`, csv([['Santri', 'Nominal', 'Jatuh tempo', 'Status'], [p.student_name || '', p.amount || 0, p.due_date || '', p.status || 'paid']])); toast('Kwitansi diunduh', 'File kwitansi berhasil dibuat.'); } return; }
    if (target.id === 'exportButton' || target.id === 'exportStaff') { event.preventDefault(); event.stopImmediatePropagation(); await exportModule(page === 'kepegawaian.html' ? 'staff' : 'students', page === 'kepegawaian.html' ? 'rekap-kepegawaian.csv' : 'rekap-santri.csv', page === 'kepegawaian.html' ? state.staff : state.students); return; }
    if (target.dataset.modal === 'articleModal') state.editingContent = null;
    if (target.dataset.liveContent) { event.preventDefault(); event.stopImmediatePropagation(); const item = state.content.find(content => content.id === target.dataset.liveContent); if (!item) return; state.editingContent = item.id; if (item.content_type === 'page') { document.getElementById('pageName').value = item.title || ''; document.getElementById('pageCopy').value = item.body || ''; openModal('pageModal'); } else { document.getElementById('articleName').value = item.title || ''; document.getElementById('articleCopy').value = item.body || ''; document.getElementById('articleType').value = [...document.getElementById('articleType').options].some(option => option.value === item.content_type) ? item.content_type : 'Artikel'; document.getElementById('articlePublish').value = item.status === 'published' ? 'publish' : 'draft'; openModal('articleModal'); } return; }
    if (target.dataset.liveBanner) { event.preventDefault(); event.stopImmediatePropagation(); const item = state.content.find(content => content.id === target.dataset.liveBanner); if (!item) return; try { const nextStatus = item.status === 'published' ? 'draft' : 'published'; await api(`admin/content/${item.id}`, json('PUT', { status: nextStatus })); await loadCms(); toast('Status banner tersimpan', 'Status banner sudah diperbarui di server.'); } catch (error) { toast('Banner belum diperbarui', error.message); } return; }
    if (target.dataset.action === 'export') { event.preventDefault(); event.stopImmediatePropagation(); if (page === 'keuangan.html') await exportModule('finance', 'laporan-keuangan.csv'); else if (page === 'notifikasi.html') await exportModule('notifications', 'riwayat-komunikasi.csv'); else await exportModule('records', 'rekap-data.csv'); return; }
    if (target.id === 'confirmBroadcast') { event.preventDefault(); event.stopImmediatePropagation(); const payload = { type: 'broadcast', channel: document.querySelector('[data-channel].active')?.dataset.channel || 'whatsapp', target: document.getElementById('broadcastTarget')?.selectedOptions[0]?.text || '', title: document.getElementById('broadcastTitle').value.trim(), message: document.getElementById('broadcastMessage').value.trim(), mode: document.getElementById('sendMode')?.value || 'now', status: document.getElementById('sendMode')?.value === 'now' ? 'sent' : 'scheduled' }; try { await saveRecord('notifications', `broadcast:${Date.now()}`, payload); closeModal('previewModal'); await loadNotifications(); toast(payload.status === 'sent' ? 'Broadcast tercatat' : 'Broadcast terjadwal', 'Riwayat komunikasi sudah diperbarui.'); } catch (error) { toast('Broadcast belum tersimpan', error.message); } return; }
    if (target.matches('[data-rule]')) { event.preventDefault(); event.stopImmediatePropagation(); target.classList.toggle('on'); target.setAttribute('aria-pressed', String(target.classList.contains('on'))); saveRecord('settings', `notification-rule:${target.dataset.rule || target.textContent.trim()}`, { type: 'notification_rule', enabled: target.classList.contains('on'), name: target.dataset.rule || target.textContent.trim() }).then(() => toast('Aturan tersimpan', 'Preferensi otomatis sudah tersimpan.')).catch(error => toast('Aturan belum tersimpan', error.message)); return; }
    if (target.id === 'backupButton' || target.id === 'backupTop') { event.preventDefault(); event.stopImmediatePropagation(); try { const result = await api('admin/export'); download(`backup-darussolah-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(result, null, 2), 'application/json'); const time = document.getElementById('backupTime'); if (time) time.textContent = 'Baru saja'; toast('Backup selesai', 'Salinan data berhasil diunduh.'); } catch (error) { toast('Backup gagal', error.message); } return; }
    if (target.id === 'restoreButton') { event.preventDefault(); event.stopImmediatePropagation(); toast('Pemulihan belum tersedia', 'Backup dapat diunduh, tetapi endpoint pemulihan belum tersedia di backend.'); return; }
    if (target.id === 'download-report') { event.preventDefault(); event.stopImmediatePropagation(); window.print(); return; }
    if (target.id === 'approval-button') { event.preventDefault(); event.stopImmediatePropagation(); const selectedClassId = document.getElementById('class-select')?.value; const students = state.students.filter(student => !selectedClassId || !student.class_id || student.class_id === selectedClassId); if (!students.length) return toast('Rapor belum siap', 'Belum ada santri pada kelas yang dipilih.'); try { await Promise.all(students.map(student => { const current = (state.records.grades || []).find(item => item.record_key === gradeKey(student.id)); return saveRecord('grades', gradeKey(student.id), { ...(current?.payload || {}), approval_status: 'pending', submitted_at: new Date().toISOString() }, student.id); })); await loadGrades(); const node = document.getElementById('approval-status'); if (node) node.textContent = 'Menunggu persetujuan kepala lembaga'; toast('Rapor diajukan', `${students.length} rapor sudah ditandai menunggu persetujuan.`); } catch (error) { toast('Pengajuan gagal', error.message); } return; }
    if (target.matches('[data-live-note]')) { event.preventDefault(); event.stopImmediatePropagation(); const studentId = target.dataset.liveNote; const current = (state.records.grades || []).find(item => item.entity_id === studentId && item.record_key === gradeKey(studentId)); const note = window.prompt('Catatan perkembangan santri', current?.payload?.note || ''); if (note === null) return; try { await saveRecord('grades', gradeKey(studentId), { ...(current?.payload || {}), note: note.trim(), scores: current?.payload?.scores || {} }, studentId); await loadGrades(); toast('Catatan tersimpan', 'Catatan akan masuk ke ringkasan rapor.'); } catch (error) { toast('Catatan belum tersimpan', error.message); } return; }
    if ((target.id === 'journal-button' || target.id === 'journal-card-button') && ['nilai.html', 'materi.html'].includes(page)) { event.preventDefault(); event.stopImmediatePropagation(); const text = window.prompt('Ringkasan jurnal pertemuan', ''); if (!text?.trim()) return; try { await saveRecord('journals', `journal:${Date.now()}`, { type: 'meeting', text: text.trim(), date: new Date().toISOString().slice(0, 10) }); toast('Jurnal tersimpan', 'Jurnal pertemuan sudah masuk ke server.'); } catch (error) { toast('Jurnal belum tersimpan', error.message); } return; }
    if (target.id === 'akhlak-button') { event.preventDefault(); event.stopImmediatePropagation(); const student = state.students[0]; if (!student) return; const text = window.prompt('Catatan akhlak dan kedisiplinan', ''); if (text === null) return; const current = (state.records.grades || []).find(item => item.entity_id === student.id && item.record_key === gradeKey(student.id)); try { await saveRecord('grades', gradeKey(student.id), { ...(current?.payload || {}), akhlak: text.trim(), scores: current?.payload?.scores || {} }, student.id); await loadGrades(); toast('Catatan akhlak tersimpan', 'Catatan sudah disiapkan untuk rapor.'); } catch (error) { toast('Catatan belum tersimpan', error.message); } return; }
    if (target.id === 'progress-button') { event.preventDefault(); event.stopImmediatePropagation(); download('progres-tahfidz.json', JSON.stringify(state.records.tahfidz || [], null, 2), 'application/json'); toast('Progres dibagikan', 'File progres live berhasil diunduh.'); return; }
    if (target.id === 'scheduleButton') { event.preventDefault(); event.stopImmediatePropagation(); const title = window.prompt('Nama jadwal mengajar', 'Sesi mengajar baru'); if (!title?.trim()) return; try { await saveRecord('schedule', `schedule:${Date.now()}`, { title: title.trim(), date: new Date().toISOString().slice(0, 10), teacher: portal()?.context?.profile?.full_name || '' }); toast('Jadwal tersimpan', 'Jadwal baru sudah masuk ke server.'); } catch (error) { toast('Jadwal belum tersimpan', error.message); } return; }
    if (target.id === 'confirmEmis') { event.preventDefault(); event.stopImmediatePropagation(); try { const result = await api('admin/export'); download(`emis-darussolah-${new Date().toISOString().slice(0, 10)}.json`, JSON.stringify(result, null, 2), 'application/json'); closeModal('emisModal'); toast('Ekspor data selesai', 'Paket data live berhasil diunduh.'); } catch (error) { toast('Ekspor gagal', error.message); } return; }
    if (target.id === 'institutionDetail') { event.preventDefault(); event.stopImmediatePropagation(); download('sebaran-santri.csv', csv([['Nama santri', 'Lembaga', 'Kelas'], ...state.students.map(student => [student.full_name, student.institution_name || '', student.class_name || ''])])); toast('Detail lembaga diunduh', 'Rekap sebaran santri berhasil dibuat.'); return; }
    if (target.id === 'installButton') { event.preventDefault(); event.stopImmediatePropagation(); if (installPrompt) { await installPrompt.prompt(); installPrompt = null; } else toast('Pemasangan belum dipicu', 'Gunakan menu browser Tambahkan ke layar utama untuk memasang aplikasi.'); return; }
    if (target.id === 'save-attendance' || target.id === 'close-session') { event.preventDefault(); event.stopImmediatePropagation(); await persistAttendance(target.id === 'close-session'); }
  }
  async function start(detail) {
    state.students = detail?.students || portal()?.students || [];
    state.classes = detail?.classes || portal()?.classes || [];
    try { if (page === 'absensi.html') return await loadAttendance(detail?.attendance || portal()?.attendance); if (page === 'santri.html') await loadStudents(); if (page === 'kepegawaian.html') await loadStaff(); if (page === 'tahfidz.html') await loadTahfidz(); if (page === 'nilai.html') await loadGrades(); if (page === 'keuangan.html') await loadFinance(); if (page === 'cms.html') await loadCms(); if (page === 'analitik.html') await loadAnalytics(); if (page === 'notifikasi.html') await loadNotifications(); if (page === 'pengaturan.html') await loadSettingsPage(); } catch (error) { toast('Data admin belum termuat', error.message); }
  }
  document.addEventListener('submit', handleSubmit, true);
  document.addEventListener('click', handleClick, true);
  document.addEventListener('change', event => {
    if (event.target.matches('[data-grade-subject]')) saveGrade(event.target);
    if (page === 'absensi.html' && event.target.matches('#student-rows .status-select')) { event.stopImmediatePropagation(); const row = event.target.closest('tr'); row.dataset.status = event.target.value; event.target.dataset.status = event.target.value; const time = row.querySelector('.time-cell'); if (time) time.textContent = ['hadir', 'terlambat'].includes(event.target.value) ? timeLabel(new Date()) : '-'; updateAttendanceStats([...document.querySelectorAll('#student-rows tr[data-attendance-student]')]); }
    if (page === 'nilai.html' && ['class-select', 'term-select'].includes(event.target.id)) renderGrades();
    if (page === 'analitik.html' && event.target.id === 'scopeSelect') {
      event.stopImmediatePropagation();
      const students = state.students.filter(item => item.institution_id === event.target.value || item.class_id === event.target.value);
      const node = document.getElementById('studentTotal'); if (node) node.textContent = String(event.target.value === 'all' ? state.students.filter(item => item.status === 'active').length : students.filter(item => item.status === 'active').length);
      return;
    }
    if (page === 'tahfidz.html' && event.target.id === 'record-student') document.querySelector('#record-target')?.focus();
  }, true);
  document.addEventListener('input', event => { const query = event.target.value.toLowerCase().trim(); if (event.target.id === 'student-search') { document.querySelectorAll('#student-list .student-card').forEach(card => { card.hidden = !card.dataset.name.includes(query); }); document.querySelectorAll('#student-rows tr[data-name]').forEach(row => { row.hidden = !row.dataset.name.includes(query); }); } if (event.target.id === 'studentSearch') document.querySelectorAll('#studentRows tr').forEach(row => { row.hidden = !row.textContent.toLowerCase().includes(query); }); if (event.target.id === 'staffSearch') document.querySelectorAll('#staffRows tr').forEach(row => { row.hidden = !row.textContent.toLowerCase().includes(query); }); if (event.target.id === 'billSearch') document.querySelectorAll('#billRows tr').forEach(row => { row.hidden = !row.textContent.toLowerCase().includes(query); }); if (event.target.id === 'contentSearch') document.querySelectorAll('#contentRows tr').forEach(row => { row.hidden = !row.textContent.toLowerCase().includes(query); }); }, true);
  window.addEventListener('darussolah:ready', event => start(event.detail), { once: true });
})();
